/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNameRouteImport } from './routes/projects_.$name'
import { Route as ApiWakatimeRouteImport } from './routes/api/wakatime'
import { Route as ApiGithubStatsRouteImport } from './routes/api/github-stats'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNameRoute = ProjectsNameRouteImport.update({
  id: '/projects_/$name',
  path: '/projects/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWakatimeRoute = ApiWakatimeRouteImport.update({
  id: '/api/wakatime',
  path: '/api/wakatime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubStatsRoute = ApiGithubStatsRouteImport.update({
  id: '/api/github-stats',
  path: '/api/github-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/github-stats': typeof ApiGithubStatsRoute
  '/api/wakatime': typeof ApiWakatimeRoute
  '/projects/$name': typeof ProjectsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/github-stats': typeof ApiGithubStatsRoute
  '/api/wakatime': typeof ApiWakatimeRoute
  '/projects/$name': typeof ProjectsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/github-stats': typeof ApiGithubStatsRoute
  '/api/wakatime': typeof ApiWakatimeRoute
  '/projects_/$name': typeof ProjectsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/github-stats'
    | '/api/wakatime'
    | '/projects/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/github-stats'
    | '/api/wakatime'
    | '/projects/$name'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/github-stats'
    | '/api/wakatime'
    | '/projects_/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiGithubStatsRoute: typeof ApiGithubStatsRoute
  ApiWakatimeRoute: typeof ApiWakatimeRoute
  ProjectsNameRoute: typeof ProjectsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$name': {
      id: '/projects_/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof ProjectsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wakatime': {
      id: '/api/wakatime'
      path: '/api/wakatime'
      fullPath: '/api/wakatime'
      preLoaderRoute: typeof ApiWakatimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-stats': {
      id: '/api/github-stats'
      path: '/api/github-stats'
      fullPath: '/api/github-stats'
      preLoaderRoute: typeof ApiGithubStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  ApiGithubStatsRoute: ApiGithubStatsRoute,
  ApiWakatimeRoute: ApiWakatimeRoute,
  ProjectsNameRoute: ProjectsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
